# Generated by Django 5.0.6 on 2024-06-11 11:21

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[crm.models.validate_phone_number])),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_contacted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, validators=[crm.models.validate_phone_number])),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Converted', 'Converted')], max_length=100)),
                ('source', models.CharField(choices=[('Website_Form', 'Website_Form'), ('Referral', 'Referral'), ('Cold_Call', 'Cold_Call'), ('Ads', 'Ads')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyThreshold',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('onepointforXdollar', models.IntegerField()),
                ('minimum_order_amount', models.FloatField()),
                ('min_points_to_redeem', models.IntegerField()),
                ('points_expiry_days', models.IntegerField()),
                ('tier_name', models.JSONField()),
                ('points_for_next_tier', models.JSONField()),
                ('tier_discount', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Toys', 'Toys'), ('Tools', 'Tools'), ('Healthcare', 'Healthcare')], default='Electronics', max_length=100)),
                ('unit_price', models.FloatField()),
                ('quantity_available', models.IntegerField()),
                ('br_code', models.CharField(max_length=100)),
                ('coin_type', models.CharField(choices=[('US_Dollar', 'US_Dollar'), ('Euro', 'Euro'), ('British_Pound', 'British_Pound'), ('Japanese_Yen', 'Japanese_Yen')], default='US_Dollar', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Coupon', 'Coupon'), ('Offer', 'Offer'), ('Discount_Code', 'Discount_Code')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Toys', 'Toys'), ('Tools', 'Tools'), ('Healthcare', 'Healthcare')], default='Electronics', max_length=100)),
                ('end_date', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed_Amount', 'Fixed_Amount')], max_length=100)),
                ('discount_value', models.FloatField()),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField(default=False)),
                ('usage_limits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('types', models.JSONField(default=list)),
                ('price', models.JSONField(default=list)),
                ('discount', models.JSONField(default=list)),
                ('duration', models.IntegerField(null=True)),
                ('duration_unit', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months'), ('Years', 'Years')], default='Months', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_id', models.PositiveIntegerField(null=True)),
                ('interaction_type', models.CharField(choices=[('Phone_Call', 'Phone Call'), ('Email', 'Email'), ('Meeting', 'Meeting')], max_length=100, null=True)),
                ('interaction_details', models.TextField(null=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('interaction_date', models.DateTimeField(null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('participant_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tier', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('loyaltyThreshold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.loyaltythreshold')),
            ],
        ),
        migrations.CreateModel(
            name='loyalRedemption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points_used', models.IntegerField(blank=True, default=0, null=True)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('LoyaltyModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.loyaltymodel')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='LoyaltyThreshold',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.loyaltythreshold'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('order_message', models.JSONField(default=dict)),
                ('loyalty_point_used', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('UnPaid', 'UnPaid'), ('Paid', 'Paid')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Credit_Card', 'Credit_Card'), ('Debit_Card', 'Debit_Card'), ('PayPal', 'PayPal'), ('Bank_Transfer', 'Bank_Transfer')], max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Sales_Representative', 'Sales Representative'), ('Customer_Support_Agent', 'Customer Support Agent'), ('Account_Manager', 'Account Manager')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedCustomer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subscription_type', models.CharField(max_length=500, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.subscription')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Subscription',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.subscription'),
        ),
    ]
