# Generated by Django 5.0.6 on 2024-05-30 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalcPoints',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('onepointforXdollar', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_contacted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted')], max_length=100)),
                ('source', models.CharField(choices=[('Website_Form', 'Website_Form'), ('Referral', 'Referral'), ('Cold_Call', 'Cold_Call'), ('Ads', 'Ads')], max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('unit_price', models.FloatField()),
                ('quantity_available', models.IntegerField()),
                ('br_code', models.CharField(max_length=100)),
                ('coin_type', models.CharField(choices=[('US_Dollar', 'US_Dollar'), ('Euro', 'Euro'), ('British_Pound', 'British_Pound'), ('Japanese_Yen', 'Japanese_Yen')], default='USD', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Coupon', 'Coupon'), ('Offer', 'Offer'), ('Discount_Code', 'Discount_Code')], max_length=100)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed_Amount', 'Fixed_Amount')], max_length=100)),
                ('discount_value', models.FloatField()),
                ('expiration_date', models.DateTimeField()),
                ('usage_limits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('Sales_Representative', 'Sales_Representative'), ('Customer_Support_Agent', 'Customer_Support_Agent'), ('Account_Manager', 'Account_Manager')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('tier', models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('CalcPoints', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.calcpoints')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Fulfilled', 'Fulfilled'), ('Cancelled', 'Cancelled')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('feedback_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('Credit_Card', 'Credit_Card'), ('Debit_Card', 'Debit_Card'), ('PayPal', 'PayPal'), ('Bank_Transfer', 'Bank_Transfer')], max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.product')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRedemption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('redemption_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.promotion')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('Lead', 'Lead'), ('Customer', 'Customer')], max_length=20, null=True)),
                ('participant_id', models.IntegerField(null=True)),
                ('interaction_type', models.CharField(choices=[('Phone_Call', 'Phone_Call'), ('Email', 'Email'), ('Meeting', 'Meeting')], max_length=100, null=True)),
                ('interaction_details', models.TextField(null=True)),
                ('outcome', models.CharField(blank=True, max_length=100)),
                ('interaction_date', models.DateTimeField(null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.user')),
            ],
        ),
    ]
