# Generated by Django 5.0.6 on 2024-06-11 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_subscription_discount_alter_subscription_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltymodel',
            old_name='points',
            new_name='total_points',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('transaction_datetime', models.DateTimeField(auto_now_add=True)),
                ('points_expiry_datetime', models.DateTimeField(null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.customer')),
                ('loyaltyThreshold', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.loyaltythreshold')),
            ],
        ),
    ]
