# Generated by Django 5.0.6 on 2024-06-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_rename_points_loyaltymodel_total_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltymodel',
            old_name='total_points',
            new_name='points',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='LoyaltyTransaction',
        ),
    ]
