# Generated by Django 5.0.6 on 2024-05-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_promotion_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Toys', 'Toys'), ('Tools', 'Tools'), ('Healthcare', 'Healthcare')], default='Electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
