# Generated by Django 5.0.6 on 2024-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_promotion_category_alter_subscription_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Furniture', 'Furniture'), ('Food', 'Food'), ('Toys', 'Toys'), ('Tools', 'Tools'), ('Healthcare', 'Healthcare')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
