# Generated by Django 5.0.6 on 2024-05-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_order_promotion_alter_subscription_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedcustomer',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
