# Generated by Django 5.0.6 on 2024-05-30 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_rename_customer_id_subscribedcustomer_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribedcustomer',
            name='Subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.subscription'),
        ),
        migrations.AddField(
            model_name='subscribedcustomer',
            name='Subscription_type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
