# Generated by Django 3.2.4 on 2024-05-31 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_subscribedcustomer_subscription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedcustomer',
            old_name='Subscription',
            new_name='subscribtion',
        ),
        migrations.RenameField(
            model_name='subscribedcustomer',
            old_name='Subscription_type',
            new_name='subscribtion_type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
