# Generated by Django 3.2.4 on 2024-05-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20240531_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedcustomer',
            old_name='subscribtion',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='subscribedcustomer',
            old_name='subscribtion_type',
            new_name='subscription_type',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
