# Generated by Django 5.0.6 on 2024-06-04 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_promotion_expired_alter_subscription_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onepointforXdollar', models.IntegerField()),
                ('minimum_order_amount', models.FloatField()),
                ('min_points_to_redeem', models.IntegerField()),
                ('points_expiry_days', models.IntegerField()),
                ('tier_name', models.CharField(max_length=50)),
                ('points_for_next_tier', models.IntegerField()),
                ('tier_discount', models.FloatField()),
                ('bonus_points_on_signup', models.IntegerField()),
                ('bonus_points_on_birthday', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='loyaltymodel',
            name='CalcPoints',
        ),
        migrations.AlterField(
            model_name='loyaltymodel',
            name='tier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='loyaltymodel',
            name='loyaltyThreshold',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.loyaltythreshold'),
        ),
        migrations.DeleteModel(
            name='CalcPoints',
        ),
    ]
