# Generated by Django 5.0.6 on 2024-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_loyaltythreshold_remove_loyaltymodel_calcpoints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyaltythreshold',
            name='bonus_points_on_birthday',
        ),
        migrations.RemoveField(
            model_name='loyaltythreshold',
            name='bonus_points_on_signup',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
