# Generated by Django 5.0.6 on 2024-06-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_order_loyaltpointsused_alter_subscription_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='LoyaltPointsUsed',
            new_name='loyalty_point_used',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
