# Generated by Django 5.0.6 on 2024-06-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_alter_subscription_discount_alter_subscription_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orignial_amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
