# Generated by Django 5.0.6 on 2024-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_order_orignial_amount_alter_subscription_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orignial_amount',
            new_name='original_amount',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='discount',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='types',
            field=models.JSONField(default=list),
        ),
    ]
